# 站群设置
[blog]
	# 绑定顶级域名
	domain = ""
	# 绑定端口
	port = 8080
	# 绑定用户id, 顶级域名内容发布者
	userid = 0
	# domain共享根目录, 缺省值 root, 共享静态文件可以放置此处
	root = ""
# 模板相关
[template]
	# 模板文件扩展名, 缺省值 .tmpl
	ext = ""
	# 所有模板库所在路径, 缺省值 views
	path = ""
	# 选用模板子目录名, 对应 path 的子目录名, 缺省值 typepress.org
	name = ""
	# layout 文件名, 缺省值 layout.html, layout 文件位于 path/name 目录下
	layout = ""
# 数据库连接
[db] # 数据库连接
	# 数据库驱动名称, 缺省值 mysql
	Driver = ""
	# host
	Host = "127.0.0.1"
	Port = 3306
	# Unix Socket 格式, Socket 和 Host 写一个就可以, Host 优先
	Socket = ""
	Database = "typepress"
	User = "root"
	Password = ""
# 日志相关, 目前只实现了文件系统日志
[log]
	# 访问日志, 子键名对应文件名
	[log.access]
		# 文件日志保存的路径
		# 设置为空值,表示不写日志
		# 重定向支持 ":stdout",":stderr" 对应 stdout, stderr
		schema = "log"
		# 记录前缀, 默认为空值
		prefix = ""
		# 日志记录格式,用 int Slice 表示, 标志值和含义如下
		# 1  Ldate         日期 年/月/日
		# 2  Ltime         时间 时:分:秒
		# 4  Lmicroseconds 时间 .毫秒于Ltime之后
		# 8  Llongfile     完整文件名:行号
		# 16 Lshortfile    文件名，此标志位优先于 Llongfile
		# 默认值Ldate 和 Ltime
		flags = []
		# 日志级别, 默认日志记录规则 0<= 记录日志 <=设定级别
		# -1 LOGLEVEL_SILENT
		#  0 LOGLEVEL_FATAL
		#  1 LOGLEVEL_ALERT
		#  2 LOGLEVEL_ERROR
		#  3 LOGLEVEL_WARN
		#  4 LOGLEVEL_CONFIG
		#  5 LOGLEVEL_INFO
		#  6 LOGLEVEL_DEBUG
		level = 5
		# 改变默认日志记录规则, 采用相等规则 记录日志 == 设定级别, 缺省值 false
		equal = false
	# 错误日志
	[log.errors]
		schema = "log"
		flags = []
		level = 2
	# 调试
	[log.debug]
		schema = ":stdout"
		flags = []
		level = 6
		equal = false
